# Site settings
title: The Central Dogma
email: 
description: "Learnings on AI + Drug Design."
baseurl: ""
url: "http://thecentraldogma.github.io"
twitter_username: thecentraldogma
github_username:  thecentraldogma

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
