# Site settings
title: The Central Dogma
email: 
description: "Learnings in AI applied to Drug Design."
baseurl: ""
url: "http://thecentraldogma.github.io"

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
